//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swiddler.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swiddler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] netprobe32 {
            get {
                object obj = ResourceManager.GetObject("netprobe32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] netprobe64 {
            get {
                object obj = ResourceManager.GetObject("netprobe64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 1,tcpmux
        ///2,compressnet
        ///3,compressnet
        ///5,rje
        ///7,echo
        ///9,discard
        ///11,systat
        ///13,daytime
        ///17,qotd
        ///18,msp
        ///19,chargen
        ///20,ftp-data
        ///21,ftp
        ///22,ssh
        ///23,telnet
        ///25,smtp
        ///27,nsw-fe
        ///29,msg-icp
        ///31,msg-auth
        ///33,dsp
        ///37,time
        ///38,rap
        ///39,rlp
        ///41,graphics
        ///42,name
        ///43,nicname
        ///44,mpm-flags
        ///45,mpm
        ///46,mpm-snd
        ///48,auditd
        ///49,tacacs
        ///50,re-mail-ck
        ///52,xns-time
        ///53,domain
        ///54,xns-ch
        ///55,isi-gl
        ///56,xns-auth
        ///58,xns-mail
        ///62,acas
        ///63,whoispp
        ///64,covia
        ///65,tacacs-ds
        ///66,sql-net
        ///67,bootps
        ///68,bootpc
        ///69,tftp
        ///70,gopher
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string port_numbers {
            get {
                return ResourceManager.GetString("port_numbers", resourceCulture);
            }
        }
    }
}
